apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    foo: 'cool huh?'
spec:
  containers:
  - name: nginx
    image: docker.io/bluebrown/busybox:v1.9 # kobold: tag: ^1; type: semver
    ports:
    - containerPort: 80
