apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    foo: 'cool huh?'
spec:
  containers:
  - name: nginx
    image: docker.io/bluebrown/busybox:20231230150010 # kobold: foo bar
    ports:
    - containerPort: 80
