apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    foo: 'cool huh?'
spec:
  containers:
  - name: nginx
    image: docker.io/bluebrown/busybox:20231230150114 # kobold: tag: v1; type: exact
    ports:
    - containerPort: 80
