apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    foo: 'cool huh?'
    grw.kobold.sh/local-path: '/tmp/kioutil-3219639970'
    grw.kobold.sh/pkg-path: '/tmp/kioutil-3219639970/manifests'
spec:
  containers:
  - name: nginx
    image: docker.io/bluebrown/busybox:v1.7@sha256:220611111e8c9bbe242e9dc1367c0fa89eef83f26203ee3f7c3764046e02b248 # kobold: tag: ^1; type: semver
    ports:
    - containerPort: 80
