apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    foo: 'cool huh?'
spec:
  containers:
  - name: nginx
    image: docker.io/bluebrown/busybox:v1.6@sha256:220611111e8c9bbe242e9dc1367c0fa89eef83f26203ee3f7c3764046e02b248 # kobold: tag: ^1; type: semver
    ports:
    - containerPort: 80
