apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    foo: 'cool huh?'
spec:
  containers:
  - name: nginx
    image: docker.io/bluebrown/busybox:v2 # kobold: tag: v2; type: exact
    ports:
    - containerPort: 80
